# Generated by Django 4.1 on 2022-09-07 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goaldenapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalBuddy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buddy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_buddy', to='goaldenapi.member')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goaldenapi.goal')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_member', to='goaldenapi.member')),
            ],
        ),
    ]
